openapi: 3.0.1
info:
  title: Demo opean api generator
  description: CRUD API
  version: 1.0.0
servers:
- url: /v2
paths:
  /customer:
    get:
      summary: Get Customer
      operationId: getCustomer
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
    post:
      summary: Add a customer
      operationId: addCustomer
      requestBody:
        description: add customer
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
        required: true
      responses:
        200:
          description: Customer Added
          content:
            application/json:
              schema:
                type: string
      x-codegen-request-body-name: customer
components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
        phone:
          type: integer
          format: int64
